
import { HeroMatch, HeroRole } from './types';

const LP = 'https://liquipedia.net';

export const HERO_MAPPINGS: HeroMatch[] = [
  // --- ASSASSINS ---
  { aovName: 'Nakroth', hokName: 'Han Xin', role: HeroRole.ASSASSIN, lane: 'Orman', description: 'Yüksek mobilite.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/9/9e/Nakroth_2020_Hero_Icon.png', hokIconUrl: LP+'/commons/images/a/af/Han_Xin_Hero_Icon.png' },
  { aovName: 'Murad', hokName: 'Li Bai', role: HeroRole.ASSASSIN, lane: 'Orman', description: 'Dokunulmazlık odaklı.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/0/05/Murad_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/9/9e/Li_Bai_Hero_Icon.png' },
  { aovName: 'Butterfly', hokName: 'Arke', role: HeroRole.ASSASSIN, lane: 'Orman', description: 'Reset mekaniği.', matchSimilarity: 95, aovIconUrl: LP+'/commons/images/3/3f/Butterfly_Hero_Icon_2019.png', hokIconUrl: LP+'/commons/images/5/53/A_Ke_Hero_Icon.png' },
  { aovName: 'Quillen', hokName: 'Arke', role: HeroRole.ASSASSIN, lane: 'Orman', description: 'Arkadan kritik hasar.', matchSimilarity: 98, aovIconUrl: LP+'/commons/images/5/58/Quillen_Hero_Icon.png', hokIconUrl: LP+'/commons/images/5/53/A_Ke_Hero_Icon.png' },
  { aovName: 'Kriknak', hokName: 'Nakoruru', role: HeroRole.ASSASSIN, lane: 'Orman', description: 'Hızlı orman temizleme.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/b/b3/Kriknak_Hero_Icon.png', hokIconUrl: LP+'/commons/images/a/ab/Nakoruru_Hero_Icon.png' },
  { aovName: 'Wukong', hokName: 'Sun Wukong', role: HeroRole.ASSASSIN, lane: 'Orman', description: 'Kritik suikastçı.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/c/c3/WuKong_2019_Hero_Icon.png', hokIconUrl: LP+'/commons/images/6/6f/Sun_Wukong_Hero_Icon.png' },
  { aovName: 'Paine', hokName: 'Sima Yi', role: HeroRole.ASSASSIN, lane: 'Orman', description: 'Gölge saldırısı.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/7/7e/Paine_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/d/d9/Sima_Yi_Hero_Icon.png' },
  { aovName: 'Zata', hokName: 'Shangguan', role: HeroRole.ASSASSIN, lane: 'Orta Koridor', description: 'Uçan büyücü suikastçı.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/d/de/Zata_Hero_Icon.png', hokIconUrl: LP+'/commons/images/0/0a/Shangguan_Wan%27er_Hero_Icon.png' },
  { aovName: 'Raz', hokName: 'Mai Shiranui', role: HeroRole.ASSASSIN, lane: 'Orta Koridor', description: 'Dürtme ve kombo.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/c/ca/Raz_Hero_Icon.png', hokIconUrl: LP+'/commons/images/1/13/Mai_Shiranui_Hero_Icon.png' },
  { aovName: 'Kaine', hokName: 'Gao Changgong', role: HeroRole.ASSASSIN, lane: 'Orman', description: 'Sürekli görünmezlik.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/thumb/c/cb/Kaine_Hero_Icon.png/180px-Kaine_Hero_Icon.png', hokIconUrl: LP+'/commons/images/c/c6/Lan_Ling_Wan_Hero_Icon.png' },
  { aovName: 'Enzo', hokName: 'Xuance', role: HeroRole.ASSASSIN, lane: 'Orman', description: 'Kanca ustası.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/9/92/Enzo_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/e/ef/BaiLi_XuanCe_Hero_Icon.png' },
  { aovName: 'Aoi', hokName: 'Jing', role: HeroRole.ASSASSIN, lane: 'Orman', description: 'Yüksek mobilite ve kanca.', matchSimilarity: 90, aovIconUrl: LP+'/commons/images/8/8f/Aoi_Hero_Icon.png', hokIconUrl: LP+'/commons/images/6/6f/Jing_HOK_Hero_Icon.jpg' },

  // --- MAGES ---
  { aovName: 'Veera', hokName: 'Daji', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'CC ve anlık hasar.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/4/49/Veera_hero_icon_2022.jpg', hokIconUrl: LP+'/commons/images/3/39/Daji_Hero_Icon.png' },
  { aovName: 'Krixi', hokName: 'Xiao Qiao', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Geniş alan hasarı.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/4/44/Krixi_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/f/f9/Xiao_Qiao_Hero_Icon.png' },
  { aovName: 'Natalya', hokName: 'Angela', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Ölümcül lazer.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/6/69/Natalya_Hero_New_Icon.jpg', hokIconUrl: LP+'/commons/images/5/5a/Angela_Hero_Icon.png' },
  { aovName: 'Tulen', hokName: 'Kongming', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Pasif hasarı odaklı.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/4/47/Tulen_Hero_New_Icon.jpg', hokIconUrl: LP+'/commons/images/4/4e/Zhuge_Liang_Hero_Icon.png' },
  { aovName: 'Lauriel', hokName: 'Diaochan', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Sürekli yetenek kullanımı.', matchSimilarity: 98, aovIconUrl: LP+'/commons/images/7/70/Lauriel_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/a/a9/KOG_Diaochan_Hero_Icon.png' },
  { aovName: 'Diao Chan', hokName: 'Wang Zhaojun', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Dondurma ve yavaşlatma.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/3/38/Diao_chan_2019_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/1/1f/Wang_Zhaojun_Hero_Icon.png' },
  { aovName: 'Aleister', hokName: 'Liang', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Mutlak kontrol.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/thumb/5/56/Aleister_hero_icon_2022.jpg/180px-Aleister_hero_icon_2022.jpg', hokIconUrl: LP+'/commons/images/b/bd/Zhang_Liang_2019.jpg' },
  { aovName: 'Mganga', hokName: 'Dr Bian', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Zehir ve şifa.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/1/1b/Mganga_Hero_Icon_2022.png', hokIconUrl: LP+'/commons/images/2/26/Bian_Que_Hero_Icon.png' },
  { aovName: 'Kahlii', hokName: 'Nuwa', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Geniş menzilli atışlar.', matchSimilarity: 85, aovIconUrl: LP+'/commons/images/8/84/Kahlii_Hero_Icon.png', hokIconUrl: LP+'/commons/images/0/03/Nuwa_Hero_Icon.png' },
  { aovName: 'Ignis', hokName: 'Zhou Yu', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Ateş ve alan hasarı.', matchSimilarity: 80, aovIconUrl: LP+'/commons/images/e/ef/Ignis_Hero_Icon.png', hokIconUrl: LP+'/commons/images/4/4a/Zhou_Yu_Hero_Icon.png' },
  { aovName: 'Ilumia', hokName: 'Nuwa', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Global ulti ve CC.', matchSimilarity: 90, aovIconUrl: LP+'/commons/images/8/87/Ilumia_Hero_Icon.png', hokIconUrl: LP+'/commons/images/0/03/Nuwa_Hero_Icon.png' },
  { aovName: 'Preyta', hokName: 'Ziya', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Ejderha süvarisi ve itme.', matchSimilarity: 75, aovIconUrl: LP+'/commons/images/9/9c/Preyta_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/3/33/Jiang_Ziya_Hero_Icon_2022.jpg' },
  { aovName: 'Marja', hokName: 'Mi Yue', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Can çalma ve dokunulmazlık.', matchSimilarity: 95, aovIconUrl: LP+'/commons/images/6/6d/Marja_Hero_Icon.png', hokIconUrl: LP+'/commons/images/7/7d/Mi_Yue_Hero_Icon.png' },
  { aovName: 'Sephera', hokName: 'Yang Yuhuan', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Müzik ve şifa.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/4/4c/Sephera_Hero_Icon.png', hokIconUrl: LP+'/commons/images/7/76/Yang_Yuhuan_Hero_Icon.png' },
  { aovName: 'Dirak', hokName: 'Lady Zhen', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Kalkan ve enerji dalgaları.', matchSimilarity: 80, aovIconUrl: LP+'/commons/images/2/23/Dirak_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/c/c1/Zhen_Ji_2019.jpg' },
  { aovName: 'Lorion', hokName: 'Yixing', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Top kontrolü ve alan.', matchSimilarity: 85, aovIconUrl: LP+'/commons/images/d/df/Lorion_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/b/bd/Yi_Xing_2022_Hero_Icon.png' },

  // --- WARRIORS ---
  { aovName: 'Arthur', hokName: 'Arthur', role: HeroRole.WARRIOR, lane: 'Karanlık Koridor', description: 'Dayanıklı savaşçı.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/6/6f/Arthur_hero_icon_2022.jpg', hokIconUrl: LP+'/commons/images/b/b5/Arthur_HOK_Hero_Icon.png' },
  { aovName: 'Lu Bu', hokName: 'Cao Cao', role: HeroRole.WARRIOR, lane: 'Karanlık Koridor', description: 'Yüksek can çalma.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/a/a9/Lubu_2019_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/0/00/Cao_Cao_Hero_Icon.png' },
  { aovName: 'Maloch', hokName: 'Lu Bu', role: HeroRole.WARRIOR, lane: 'Karanlık Koridor', description: 'Gerçek hasar vuran dev.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/4/4c/Maloch_Hero_Icon_2019.png', hokIconUrl: LP+'/commons/images/2/2f/Lu_Bu_2022_Hero_Icon.png' },
  { aovName: 'Yena', hokName: 'Mulan', role: HeroRole.WARRIOR, lane: 'Karanlık Koridor', description: 'Çift formlu kombo kraliçesi.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/7/73/Yena_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/d/d4/Hua_Mulan_Hero_Icon.png' },
  { aovName: 'Omen', hokName: 'Lao Fuzi', role: HeroRole.WARRIOR, lane: 'Karanlık Koridor', description: 'Rakibi hapsetme.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/0/08/Omen_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/7/7b/Lao_Fu_Zi_Hero_Icon.png' },
  { aovName: 'Ryoma', hokName: 'Ukyo Tachibana', role: HeroRole.WARRIOR, lane: 'Karanlık Koridor', description: 'Hızlı saldırı ve menzil.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/0/0d/Ryoma_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/b/b3/Ukyo_Tachibana_Hero_Icon.png' },
  { aovName: 'Richter', hokName: 'Guan Yu', role: HeroRole.WARRIOR, lane: 'Karanlık Koridor', description: 'Zemin bazlı saldırı.', matchSimilarity: 90, aovIconUrl: LP+'/commons/images/f/fa/Richter_Hero_Icon.png', hokIconUrl: LP+'/commons/images/2/21/Guan_Yu_Hero_Icon.png' },
  { aovName: 'Veres', hokName: 'Ying', role: HeroRole.WARRIOR, lane: 'Karanlık Koridor', description: 'Zincir silahı ve pasif.', matchSimilarity: 95, aovIconUrl: LP+'/commons/images/1/17/Veres_Hero_Icon.png', hokIconUrl: LP+'/commons/images/d/d8/Yun_Ying_Hero_Icon.png' },
  { aovName: 'Kil\'Groth', hokName: 'Dian Wei', role: HeroRole.WARRIOR, lane: 'Karanlık Koridor', description: 'Saldırı hızı canavarı.', matchSimilarity: 85, aovIconUrl: LP+'/commons/images/f/f1/Kil%27Groth_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/e/ec/Dian_Wei_Hero_Icon.png' },
  { aovName: 'Florentino', hokName: 'Mayene', role: HeroRole.WARRIOR, lane: 'Karanlık Koridor', description: 'Çoklu kombo ve çiçekler.', matchSimilarity: 80, aovIconUrl: LP+'/commons/images/5/59/Florentino_Hero_Icon.png', hokIconUrl: LP+'/commons/images/d/d2/Ji_Xiaoman_Hero_Icon.png' },
  { aovName: 'Amily', hokName: 'Kaizer', role: HeroRole.WARRIOR, lane: 'Karanlık Koridor', description: 'Tekli hedefte güçlü tekmeler.', matchSimilarity: 85, aovIconUrl: LP+'/commons/images/7/7c/Amily_Hero_Icon.png', hokIconUrl: LP+'/commons/images/a/aa/Kai_Hero_Icon.png' },
  { aovName: 'Zanis', hokName: 'Zilong', role: HeroRole.WARRIOR, lane: 'Orman', description: 'Zıplama ve ani hasar.', matchSimilarity: 95, aovIconUrl: LP+'/commons/images/4/41/Zanis_2019_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/9/97/Zhao_Yun_Hero_Icon.png' },
  { aovName: 'Allain', hokName: 'Allain', role: HeroRole.WARRIOR, lane: 'Karanlık Koridor', description: 'Sürekli vuruş odaklı.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/5/5f/Allain_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/5/5f/Allain_Hero_Icon.jpg' },
  { aovName: 'Bijan', hokName: 'Bijan', role: HeroRole.WARRIOR, lane: 'Karanlık Koridor', description: 'Hayvan üzerinde saldırı.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/4/44/Bijan_Hero_Icon.png', hokIconUrl: LP+'/commons/images/4/44/Bijan_Hero_Icon.png' },

  // --- MARKSMEN ---
  { aovName: 'Valhein', hokName: 'Di Renjie', role: HeroRole.MARKSMAN, lane: 'Ejderha Koridoru', description: 'Hızlı kart atışları.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/6/63/Valhein_Hero_Icon.png', hokIconUrl: LP+'/commons/images/9/94/Di_Renjie_Hero_Icon.png' },
  { aovName: 'Violet', hokName: 'Lady Sun', role: HeroRole.MARKSMAN, lane: 'Ejderha Koridoru', description: 'Takla atarak vurma.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/7/73/Violet_2019_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/4/40/Sun_Shangxiang_Hero_Icon.png' },
  { aovName: 'Yorn', hokName: 'Hou Yi', role: HeroRole.MARKSMAN, lane: 'Ejderha Koridoru', description: 'Global ok ultisi.', matchSimilarity: 95, aovIconUrl: LP+'/commons/images/0/05/Yorn_Hero_Icon_2019.png', hokIconUrl: LP+'/commons/images/4/49/Hou_Yi_Hero_Icon.png' },
  { aovName: 'Elsu', hokName: 'Shouyue', role: HeroRole.MARKSMAN, lane: 'Ejderha Koridoru', description: 'Keskin nişancı tüfeği.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/8/88/Elsu_Hero_Icon.png', hokIconUrl: LP+'/commons/images/9/9c/BaiLi_ShouYue_Hero_Icon.png' },
  { aovName: 'Hayate', hokName: 'Marco Polo', role: HeroRole.MARKSMAN, lane: 'Ejderha Koridoru', description: 'Gerçek hasar mermileri.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/4/45/Hayate_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/5/58/Marco_Polo_Hero_Icon.png' },
  { aovName: 'Tel\'Annas', hokName: 'Garo', role: HeroRole.MARKSMAN, lane: 'Ejderha Koridoru', description: 'Uzun menzilli oklar.', matchSimilarity: 90, aovIconUrl: LP+'/commons/images/0/01/Tel%27Annas_Hero_New_Icon.jpg', hokIconUrl: LP+'/commons/images/b/b8/Jia_Luo_Hero_Icon.png' },
  { aovName: 'Fennik', hokName: 'Fang', role: HeroRole.MARKSMAN, lane: 'Orman', description: 'Bomba bırakma.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/a/ac/Fennik_Hero_Icon.png', hokIconUrl: LP+'/commons/images/c/cb/Li_Yuanfang_Hero_Icon.png' },
  { aovName: 'Slimz', hokName: 'Fang', role: HeroRole.MARKSMAN, lane: 'Ejderha Koridoru', description: 'Mızrak fırlatma.', matchSimilarity: 80, aovIconUrl: LP+'/commons/images/2/25/Slimz_Hero_Icon.png', hokIconUrl: LP+'/commons/images/c/cb/Li_Yuanfang_Hero_Icon.png' },
  { aovName: 'Moren', hokName: 'Huang Zhong', role: HeroRole.MARKSMAN, lane: 'Ejderha Koridoru', description: 'Dayanıklı nişancı.', matchSimilarity: 85, aovIconUrl: LP+'/commons/images/thumb/a/a5/Moren_2026_Hero_Icon.jpg/180px-Moren_2026_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/0/0a/Huang_Zhong_Hero_Icon.png' },
  { aovName: 'Laville', hokName: 'Hou Yi', role: HeroRole.MARKSMAN, lane: 'Ejderha Koridoru', description: 'Seri atışlar.', matchSimilarity: 90, aovIconUrl: LP+'/commons/images/7/72/Laville_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/4/49/Hou_Yi_Hero_Icon.png' },
  { aovName: 'Erin', hokName: 'Erin', role: HeroRole.MARKSMAN, lane: 'Ejderha Koridoru', description: 'Büyücü nişancı.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/8/87/Ailin_Hero_Icon.png', hokIconUrl: LP+'/commons/images/8/87/Ailin_Hero_Icon.png' },
  { aovName: 'Teeri', hokName: 'Lady Zhen', role: HeroRole.MARKSMAN, lane: 'Ejderha Koridoru', description: 'Seken atışlar.', matchSimilarity: 75, aovIconUrl: LP+'/commons/images/e/e7/Teeri_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/c/c1/Zhen_Ji_2019.jpg' },

  // --- SUPPORTS / TANKS ---
  { aovName: 'Alice', hokName: 'Sun Bin', role: HeroRole.SUPPORT, lane: 'Destek', description: 'Zamanı yavaşlatma.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/9/9c/Alice_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/d/d9/Sun_Bin_Hero_Icon.png' },
  { aovName: 'Grakk', hokName: 'Zhong Kui', role: HeroRole.TANK, lane: 'Destek', description: 'Kanca ustası.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/f/fb/Grakk_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/b/b4/Zhong_Kui_Hero_Icon.png' },
  { aovName: 'Helen', hokName: 'Cai Yan', role: HeroRole.SUPPORT, lane: 'Destek', description: 'Alan şifası.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/thumb/e/e1/Helen_Hero_Icon.jpg/180px-Helen_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/f/f8/Cai_Wenji_Hero_Icon.png' },
  { aovName: 'Aya', hokName: 'Yaria', role: HeroRole.SUPPORT, lane: 'Destek', description: 'Bağlanma koruması.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/0/0b/Aya_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/d/d3/Yao_Hero_Icon.png' },
  { aovName: 'Rouie', hokName: 'Da Qiao', role: HeroRole.SUPPORT, lane: 'Destek', description: 'Işınlanma kapıları.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/6/61/Rouie_Hero_Icon.png', hokIconUrl: LP+'/commons/images/3/30/Da_Qiao_Hero_Icon.png' },
  { aovName: 'Thane', hokName: 'Xiang Yu', role: HeroRole.TANK, lane: 'Destek', description: 'İttirme ve dayanıklılık.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/1/14/Thane_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/a/ac/Xiang_Yu_Hero_Icon.png' },
  { aovName: 'Mina', hokName: 'Bai Qi', role: HeroRole.TANK, lane: 'Destek', description: 'Kışkırtma mekaniği.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/3/38/Mina_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/f/fb/Bai_Qi_Hero_Icon.png' },
  { aovName: 'Cresht', hokName: 'Zhang Fei', role: HeroRole.TANK, lane: 'Destek', description: 'Canavara dönüşme.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/c/c6/Cresht_Hero_Icon_2019.png', hokIconUrl: LP+'/commons/images/9/9e/Zhang_Fei_Hero_Icon.png' },
  { aovName: 'Baldum', hokName: 'Lian Po', role: HeroRole.TANK, lane: 'Destek', description: 'Rakipleri gömme.', matchSimilarity: 85, aovIconUrl: LP+'/commons/images/0/09/Baldum_Hero_Icon.png', hokIconUrl: LP+'/commons/images/2/20/Lian_Po_Hero_Icon.png' },
  { aovName: 'Arum', hokName: 'Donghuang Taiyi', role: HeroRole.TANK, lane: 'Destek', description: 'Bağlama ve can emme.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/5/5b/Arum_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/7/73/East_Emperor_Taiyi_Hero_Icon.png' },
  { aovName: 'Chaugnar', hokName: 'Zhuangzi', role: HeroRole.TANK, lane: 'Destek', description: 'CC temizleme.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/f/f5/Chaugnar_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/b/b0/Zhuang_Zhou_Hero_Icon.png' },
  { aovName: 'Omega', hokName: 'Liu Shan', role: HeroRole.TANK, lane: 'Destek', description: 'Kule dondurma.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/6/6d/Omega_Hero_Icon_2020.jpg', hokIconUrl: LP+'/commons/images/7/76/Liu_Shan_Hero_Icon.png' },
  { aovName: 'Xeniel', hokName: 'Liu Bang', role: HeroRole.TANK, lane: 'Destek', description: 'Global ışınlanma.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/2/28/Xeniel_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/6/67/Liu_Bang_Hero_Icon.png' },
  { aovName: 'Toro', hokName: 'Lian Po', role: HeroRole.TANK, lane: 'Destek', description: 'Dayanıklı boğa.', matchSimilarity: 90, aovIconUrl: LP+'/commons/images/1/12/Toro_Hero_Icon.png', hokIconUrl: LP+'/commons/images/2/20/Lian_Po_Hero_Icon.png' },
  { aovName: 'Lumburr', hokName: 'Lian Po', role: HeroRole.TANK, lane: 'Destek', description: 'Yeri sarsma.', matchSimilarity: 80, aovIconUrl: LP+'/commons/images/d/de/Lumburr_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/2/20/Lian_Po_Hero_Icon.png' },
  { aovName: 'Ata', hokName: 'Ata', role: HeroRole.TANK, lane: 'Destek', description: 'Duvar örme.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/3/35/Ata_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/3/35/Ata_Hero_Icon.jpg' },
  { aovName: 'Dolia', hokName: 'Dolia', role: HeroRole.SUPPORT, lane: 'Destek', description: 'Ulti sıfırlama.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/4/43/Doria_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/4/43/Doria_Hero_Icon.jpg' },
  { aovName: 'Heino', hokName: 'Heino', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Zaman geri alma.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/4/47/Heino_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/4/47/Heino_Hero_Icon.jpg' },
  { aovName: 'Biron', hokName: 'Biron', role: HeroRole.WARRIOR, lane: 'Karanlık Koridor', description: 'Kalkan ve enerji.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/1/12/Kuang_Tie_Hero_Icon.png', hokIconUrl: LP+'/commons/images/1/12/Kuang_Tie_Hero_Icon.png' }
];
