
import { HeroMatch, HeroRole } from './types';

const LP = 'https://liquipedia.net';

export const HERO_MAPPINGS: HeroMatch[] = [
  // --- ASSASSINS ---
  { aovName: 'Nakroth', hokName: 'Han Xin', role: HeroRole.ASSASSIN, lane: 'Orman', description: 'Yüksek mobilite ve orman temizleme hızı.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/9/9e/Nakroth_2020_Hero_Icon.png', hokIconUrl: LP+'/commons/images/a/af/Han_Xin_Hero_Icon.png' },
  { aovName: 'Murad', hokName: 'Li Bai', role: HeroRole.ASSASSIN, lane: 'Orman', description: 'Dokunulmazlık ve ani baskın yeteneği.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/0/05/Murad_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/9/9e/Li_Bai_Hero_Icon.png' },
  { aovName: 'Butterfly', hokName: 'A Ke', role: HeroRole.ASSASSIN, lane: 'Orman', description: 'Skor aldıkça yetenek sıfırlama.', matchSimilarity: 95, aovIconUrl: LP+'/commons/images/3/3f/Butterfly_Hero_Icon_2019.png', hokIconUrl: LP+'/commons/images/5/53/A_Ke_Hero_Icon.png' },
  { aovName: 'Quillen', hokName: 'A Ke', role: HeroRole.ASSASSIN, lane: 'Orman', description: 'Arkadan vuruşlarda %100 kritik hasar.', matchSimilarity: 98, aovIconUrl: LP+'/commons/images/5/58/Quillen_Hero_Icon.png', hokIconUrl: LP+'/commons/images/5/53/A_Ke_Hero_Icon.png' },
  { aovName: 'Kriknak', hokName: 'Nakoruru', role: HeroRole.ASSASSIN, lane: 'Orman', description: 'Yüksek anlık fiziksel hasar.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/b/b3/Kriknak_Hero_Icon.png', hokIconUrl: LP+'/commons/images/a/ab/Nakoruru_Hero_Icon.png' },
  { aovName: 'Paine', hokName: 'Sima Yi', role: HeroRole.ASSASSIN, lane: 'Orman', description: 'Gölge formuyla uzun mesafeli baskın.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/7/7e/Paine_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/d/d9/Sima_Yi_Hero_Icon.png' },
  { aovName: 'Zata', hokName: 'Shangguan Wan\'er', role: HeroRole.ASSASSIN, lane: 'Orta Koridor', description: 'Kombolar sonrası uçuş ve dokunulmazlık.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/d/de/Zata_Hero_Icon.png', hokIconUrl: LP+'/commons/images/0/0a/Shangguan_Wan%27er_Hero_Icon.png' },
  { aovName: 'Keera', hokName: 'Zhao Yun', role: HeroRole.ASSASSIN, lane: 'Orman', description: 'Duvarların içinden geçme yeteneği.', matchSimilarity: 80, aovIconUrl: LP+'/commons/images/7/74/Keera_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/9/97/Zhao_Yun_Hero_Icon.png' },
  { aovName: 'Enzo', hokName: 'Bai Li Xuan Ce', role: HeroRole.ASSASSIN, lane: 'Orman', description: 'Zincirli kancasıyla düşmanları savurur.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/9/92/Enzo_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/e/ef/BaiLi_XuanCe_Hero_Icon.png' },
  { aovName: 'Aoi', hokName: 'Jing', role: HeroRole.ASSASSIN, lane: 'Orman', description: 'Pençeleriyle yüksek mobilite sağlar.', matchSimilarity: 90, aovIconUrl: LP+'/commons/images/8/8f/Aoi_Hero_Icon.png', hokIconUrl: LP+'/commons/images/6/6f/Jing_HOK_Hero_Icon.jpg' },
  { aovName: 'Airi', hokName: 'Hua Mulan', role: HeroRole.ASSASSIN, lane: 'Karanlık Koridor', description: 'Ninja çevikliği ve sersemletme.', matchSimilarity: 85, aovIconUrl: LP+'/commons/images/7/75/Airi_Hero_New_Icon.jpg', hokIconUrl: LP+'/commons/images/d/d4/Hua_Mulan_Hero_Icon.png' },

  // --- MAGES ---
  { aovName: 'Veera', hokName: 'Daji', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Tekli hedeflere yüksek büyü hasarı.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/4/49/Veera_hero_icon_2022.jpg', hokIconUrl: LP+'/commons/images/3/39/Daji_Hero_Icon.png' },
  { aovName: 'Krixi', hokName: 'Xiao Qiao', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Geniş alan etkili büyü yetenekleri.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/4/44/Krixi_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/f/f9/Xiao_Qiao_Hero_Icon.png' },
  { aovName: 'Natalya', hokName: 'Angela', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Lazer saldırısıyla yüksek eritme hasarı.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/6/69/Natalya_Hero_New_Icon.jpg', hokIconUrl: LP+'/commons/images/5/5a/Angela_Hero_Icon.png' },
  { aovName: 'Tulen', hokName: 'Zhuge Liang', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Yıldırım patlamaları ve mobil büyücü.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/4/47/Tulen_Hero_New_Icon.jpg', hokIconUrl: LP+'/commons/images/4/4e/Zhuge_Liang_Hero_Icon.png' },
  { aovName: 'Lauriel', hokName: 'Diaochan', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Yetenek spamı ve gerçek hasar.', matchSimilarity: 98, aovIconUrl: LP+'/commons/images/7/70/Lauriel_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/a/a9/KOG_Diaochan_Hero_Icon.png' },
  { aovName: 'Diao Chan', hokName: 'Wang Zhaojun', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Düşmanları dondurma ve yavaşlatma.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/3/38/Diao_chan_2019_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/1/1f/Wang_Zhaojun_Hero_Icon.png' },
  { aovName: 'Aleister', hokName: 'Zhang Liang', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Durdurulamaz kitle kontrolü.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/thumb/5/56/Aleister_hero_icon_2022.jpg/180px-Aleister_hero_icon_2022.jpg', hokIconUrl: LP+'/commons/images/b/bd/Zhang_Liang_2019.jpg' },
  { aovName: 'Mganga', hokName: 'Bian Que', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Zehir yükleri biriktirerek hasar ve iyileştirme.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/1/1b/Mganga_Hero_Icon_2022.png', hokIconUrl: LP+'/commons/images/2/26/Bian_Que_Hero_Icon.png' },
  { aovName: 'Ignis', hokName: 'Zhou Yu', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Ateşle alanı kontrol eder.', matchSimilarity: 80, aovIconUrl: LP+'/commons/images/e/ef/Ignis_Hero_Icon.png', hokIconUrl: LP+'/commons/images/4/4a/Zhou_Yu_Hero_Icon.png' },
  { aovName: 'Ilumia', hokName: 'Nuwa', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Global harita kontrolü ve sersemletme.', matchSimilarity: 90, aovIconUrl: LP+'/commons/images/8/87/Ilumia_Hero_Icon.png', hokIconUrl: LP+'/commons/images/0/03/Nuwa_Hero_Icon.png' },
  { aovName: 'Marja', hokName: 'Mi Yue', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Can çalma ve ölümsüzlük formu.', matchSimilarity: 95, aovIconUrl: LP+'/commons/images/6/6d/Marja_Hero_Icon.png', hokIconUrl: LP+'/commons/images/7/7d/Mi_Yue_Hero_Icon.png' },
  { aovName: 'Sephera', hokName: 'Yang Yuhuan', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Su yetenekleriyle hasar ve destek sağlar.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/4/4c/Sephera_Hero_Icon.png', hokIconUrl: LP+'/commons/images/7/76/Yang_Yuhuan_Hero_Icon.png' },
  { aovName: 'Dirak', hokName: 'Zhen Ji', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Enerji kalkanı ve güçlü itme.', matchSimilarity: 80, aovIconUrl: LP+'/commons/images/2/23/Dirak_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/c/c1/Zhen_Ji_2019.jpg' },
  { aovName: 'Lorion', hokName: 'Yi Xing', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Elektrikli kürelerle alan kontrolü.', matchSimilarity: 85, aovIconUrl: LP+'/commons/images/d/df/Lorion_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/b/bd/Yi_Xing_2022_Hero_Icon.png' },
  { aovName: 'Yue', hokName: 'Gan Jiang & Mo Ye', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Uzun menzilli keskin kılıç saldırıları.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/3/3f/Yue_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/4/43/Gan_Jiang_Mo_Ye_Hero_Icon.png' },
  { aovName: 'Iggy', hokName: 'Shen Mengxi', role: HeroRole.MAGE, lane: 'Orta Koridor', description: 'Bomba atarak yüksek baskı kurar.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/9/9b/Iggy_Hero_Icon.png', hokIconUrl: LP+'/commons/images/c/ce/Shen_Mengxi_Hero_Icon.png' },

  // --- WARRIORS ---
  { aovName: 'Arthur', hokName: 'Arthur', role: HeroRole.WARRIOR, lane: 'Karanlık Koridor', description: 'Dengeli defans ve ofans özellikleri.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/6/6f/Arthur_hero_icon_2022.jpg', hokIconUrl: LP+'/commons/images/b/b5/Arthur_HOK_Hero_Icon.png' },
  { aovName: 'Lu Bu', hokName: 'Cao Cao', role: HeroRole.WARRIOR, lane: 'Karanlık Koridor', description: 'Yüksek can çalma ve dayanıklılık.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/a/a9/Lubu_2019_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/0/00/Cao_Cao_Hero_Icon.png' },
  { aovName: 'Maloch', hokName: 'Lu Bu', role: HeroRole.WARRIOR, lane: 'Karanlık Koridor', description: 'Gerçek hasar vuran dev kılıç.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/4/4c/Maloch_Hero_Icon_2019.png', hokIconUrl: LP+'/commons/images/2/2f/Lu_Bu_2022_Hero_Icon.png' },
  { aovName: 'Yena', hokName: 'Hua Mulan', role: HeroRole.WARRIOR, lane: 'Karanlık Koridor', description: 'Çift formlu kombo ustası.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/7/73/Yena_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/d/d4/Hua_Mulan_Hero_Icon.png' },
  { aovName: 'Omen', hokName: 'Old Master', role: HeroRole.WARRIOR, lane: 'Karanlık Koridor', description: 'Düşmanı bir alana hapseder.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/0/08/Omen_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/7/7b/Lao_Fu_Zi_Hero_Icon.png' },
  { aovName: 'Ryoma', hokName: 'Ukyo Tachibana', role: HeroRole.WARRIOR, lane: 'Karanlık Koridor', description: 'Hızlı samuray kesişleri.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/0/0d/Ryoma_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/b/b3/Ukyo_Tachibana_Hero_Icon.png' },
  { aovName: 'Veres', hokName: 'Yun Ying', role: HeroRole.WARRIOR, lane: 'Karanlık Koridor', description: 'Zinciriyle orta menzilli dövüşçü.', matchSimilarity: 95, aovIconUrl: LP+'/commons/images/1/17/Veres_Hero_Icon.png', hokIconUrl: LP+'/commons/images/d/d8/Yun_Ying_Hero_Icon.png' },
  { aovName: 'Florentino', hokName: 'Mayene', role: HeroRole.WARRIOR, lane: 'Karanlık Koridor', description: 'Çiçek toplayarak seri kombolar yapar.', matchSimilarity: 80, aovIconUrl: LP+'/commons/images/5/59/Florentino_Hero_Icon.png', hokIconUrl: LP+'/commons/images/d/d2/Ji_Xiaoman_Hero_Icon.png' },
  { aovName: 'Bijan', hokName: 'Bijan', role: HeroRole.WARRIOR, lane: 'Karanlık Koridor', description: 'Kum canavarıyla haritada gezer.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/4/44/Bijan_Hero_Icon.png', hokIconUrl: LP+'/commons/images/4/44/Bijan_Hero_Icon.png' },
  { aovName: 'Errol', hokName: 'Biron', role: HeroRole.WARRIOR, lane: 'Karanlık Koridor', description: 'Elektrikli saldırılar ve kalkan.', matchSimilarity: 90, aovIconUrl: LP+'/commons/images/1/12/Kuang_Tie_Hero_Icon.png', hokIconUrl: LP+'/commons/images/1/12/Kuang_Tie_Hero_Icon.png' },
  { aovName: 'Amily', hokName: 'Kaizer', role: HeroRole.WARRIOR, lane: 'Karanlık Koridor', description: 'Tekli hedeflere kritik tekmeler.', matchSimilarity: 85, aovIconUrl: LP+'/commons/images/7/7c/Amily_Hero_Icon.png', hokIconUrl: LP+'/commons/images/a/aa/Kai_Hero_Icon.png' },
  { aovName: 'Zanis', hokName: 'Zhao Yun', role: HeroRole.WARRIOR, lane: 'Orman', description: 'Hız ve mızrak saldırıları.', matchSimilarity: 95, aovIconUrl: LP+'/commons/images/4/41/Zanis_2019_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/9/97/Zhao_Yun_Hero_Icon.png' },

  // --- MARKSMEN ---
  { aovName: 'Valhein', hokName: 'Di Renjie', role: HeroRole.MARKSMAN, lane: 'Ejderha Koridoru', description: 'Farklı etkili kartlar fırlatır.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/6/63/Valhein_Hero_Icon.png', hokIconUrl: LP+'/commons/images/9/94/Di_Renjie_Hero_Icon.png' },
  { aovName: 'Violet', hokName: 'Sun Shangxiang', role: HeroRole.MARKSMAN, lane: 'Ejderha Koridoru', description: 'Takla atarak güçlendirilmiş vuruş yapar.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/7/73/Violet_2019_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/4/40/Sun_Shangxiang_Hero_Icon.png' },
  { aovName: 'Yorn', hokName: 'Hou Yi', role: HeroRole.MARKSMAN, lane: 'Ejderha Koridoru', description: 'Seri ok yağmuru ve global ok.', matchSimilarity: 95, aovIconUrl: LP+'/commons/images/0/05/Yorn_Hero_Icon_2019.png', hokIconUrl: LP+'/commons/images/4/49/Hou_Yi_Hero_Icon.png' },
  { aovName: 'Elsu', hokName: 'Bai Li Shou Yue', role: HeroRole.MARKSMAN, lane: 'Ejderha Koridoru', description: 'Keskin nişancı atışları ve görünmezlik.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/8/88/Elsu_Hero_Icon.png', hokIconUrl: LP+'/commons/images/9/9c/BaiLi_ShouYue_Hero_Icon.png' },
  { aovName: 'Hayate', hokName: 'Marco Polo', role: HeroRole.MARKSMAN, lane: 'Ejderha Koridoru', description: 'Gerçek hasar veren mermiler.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/4/45/Hayate_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/5/58/Marco_Polo_Hero_Icon.png' },
  { aovName: 'Tel\'Annas', hokName: 'Garo', role: HeroRole.MARKSMAN, lane: 'Ejderha Koridoru', description: 'Yüksek menzilli ve yavaşlatan oklar.', matchSimilarity: 90, aovIconUrl: LP+'/commons/images/0/01/Tel%27Annas_Hero_New_Icon.jpg', hokIconUrl: LP+'/commons/images/b/b8/Jia_Luo_Hero_Icon.png' },
  { aovName: 'Fennik', hokName: 'Li Yuanfang', role: HeroRole.MARKSMAN, lane: 'Orman', description: 'Düşmanlara bomba yerleştirir.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/a/ac/Fennik_Hero_Icon.png', hokIconUrl: LP+'/commons/images/c/cb/Li_Yuanfang_Hero_Icon.png' },
  { aovName: 'Erin', hokName: 'Erin', role: HeroRole.MARKSMAN, lane: 'Ejderha Koridoru', description: 'Büyü hasarı vuran nişancı.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/8/87/Ailin_Hero_Icon.png', hokIconUrl: LP+'/commons/images/8/87/Ailin_Hero_Icon.png' },
  { aovName: 'Capheny', hokName: 'Yu Ji', role: HeroRole.MARKSMAN, lane: 'Ejderha Koridoru', description: 'Yüksek fiziksel hasardan kaçınma.', matchSimilarity: 80, aovIconUrl: LP+'/commons/images/b/b0/Capheny_Hero_Icon.png', hokIconUrl: LP+'/commons/images/5/5e/Yu_Ji_Hero_Icon.png' },
  { aovName: 'Eland\'orr', hokName: 'Gongsun Li', role: HeroRole.MARKSMAN, lane: 'Orman', description: 'Şemsiye mekanikleriyle yüksek mobilite.', matchSimilarity: 95, aovIconUrl: LP+'/commons/images/6/6b/Eland%27orr_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/3/30/Gongsun_Li_Hero_Icon.png' },

  // --- SUPPORTS / TANKS ---
  { aovName: 'Alice', hokName: 'Sun Bin', role: HeroRole.SUPPORT, lane: 'Destek', description: 'Hızlandırma ve zaman manipülasyonu.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/9/9c/Alice_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/d/d9/Sun_Bin_Hero_Icon.png' },
  { aovName: 'Grakk', hokName: 'Zhong Kui', role: HeroRole.TANK, lane: 'Destek', description: 'Düşmanları kancasıyla yanına çeker.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/f/fb/Grakk_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/b/b4/Zhong_Kui_Hero_Icon.png' },
  { aovName: 'Helen', hokName: 'Cai Wenji', role: HeroRole.SUPPORT, lane: 'Destek', description: 'Sürekli alan iyileştirmesi.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/thumb/e/e1/Helen_Hero_Icon.jpg/180px-Helen_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/f/f8/Cai_Wenji_Hero_Icon.png' },
  { aovName: 'Aya', hokName: 'Yao', role: HeroRole.SUPPORT, lane: 'Destek', description: 'Dost kahramanların üzerine biner.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/0/0b/Aya_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/d/d3/Yao_Hero_Icon.png' },
  { aovName: 'Thane', hokName: 'Xiang Yu', role: HeroRole.TANK, lane: 'Destek', description: 'Güçlü itme ve direnç özellikleri.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/1/14/Thane_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/a/ac/Xiang_Yu_Hero_Icon.png' },
  { aovName: 'Mina', hokName: 'Bai Qi', role: HeroRole.TANK, lane: 'Destek', description: 'Düşmanları kışkırtarak kendine çeker.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/3/38/Mina_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/f/fb/Bai_Qi_Hero_Icon.png' },
  { aovName: 'Arum', hokName: 'Donghuang Taiyi', role: HeroRole.TANK, lane: 'Destek', description: 'Düşmanı kilitler ve hasarı paylaşır.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/5/5b/Arum_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/7/73/East_Emperor_Taiyi_Hero_Icon.png' },
  { aovName: 'Rouie', hokName: 'Da Qiao', role: HeroRole.SUPPORT, lane: 'Destek', description: 'Işınlanma kapıları açar.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/6/61/Rouie_Hero_Icon.png', hokIconUrl: LP+'/commons/images/3/30/Da_Qiao_Hero_Icon.png' },
  { aovName: 'Dolia', hokName: 'Dolia', role: HeroRole.SUPPORT, lane: 'Destek', description: 'Dostlarının ultisini sıfırlar.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/4/43/Doria_Hero_Icon.jpg', hokIconUrl: LP+'/commons/images/4/43/Doria_Hero_Icon.jpg' },
  { aovName: 'Ming Shiyin', hokName: 'Ming Shiyin', role: HeroRole.SUPPORT, lane: 'Destek', description: 'Dostuna bağ kurarak güç sağlar.', matchSimilarity: 100, aovIconUrl: LP+'/commons/images/c/c4/Ming_Shiyin_Hero_Icon.png', hokIconUrl: LP+'/commons/images/c/c4/Ming_Shiyin_Hero_Icon.png' }
];
